@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor "User" as user
participant "System" as sys

user -> sys : Click on Profile Settings Icon
user <-- sys : Show Profile Settings Page

user -> sys : Click on the copy token icon
user <-- sys : Sends the token to users clipboard

@enduml