@startuml
'https://plantuml.com/sequence-diagram

autonumber

autonumber

actor "User" as user
actor ":System" as sys

user -> sys: Click on the settings icon
user <-- sys: Show settings page

user -> sys: Click on the "Save App's Data" dropdown menu
user <-- sys: Show the dropdown menu's options

user -> sys: Choose the file format in which the data will be saved
user <-- sys: Save the file in the Downloads folder




@enduml