@startuml
'https://plantuml.com/class-diagram

hide circle
title Class Diagram

class Book
class WishlistedBook
class OnGoingBook
class ReadBook
class BookContainer
class Review
class Stats
class WishlistContainer
class ReviewContainer

class Library

Book <|-- WishlistedBook
Book <|-- OnGoingBook
Book *-- BookContainer
WishlistedBook *-- WishlistContainer
OnGoingBook <|-- ReadBook
Review *-- ReadBook
BookContainer *-- Stats
BookContainer *-- Library
Review *- ReviewContainer
@enduml