@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as user
participant ":System" as sys

user -> sys: Click on the profile icon
user <-- sys: Show the profile page

user -> sys: Click on the "See Wishlisted Books" button
user <-- sys: Shows all the user's wishlisted books
@enduml