@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as user
participant ":System" as sys

user -> sys: Click on the profile page icon
user <-- sys: Show profile page
user <-- sys: Shows the user review plot

@enduml