@startuml
'https://plantuml.com/component-diagram

left to right direction
title Physical Architecture Diagram

node "Android Device" as android_device {
    component "CoverToCover" as android_ctc
}

component "CoverToCover" as ctc {
    component "Adapter" as adapter
    component "API" as api
    component "DataModels" as datamodels
    component "Exceptions" as exceptions
    component "Models" as models
    component "Repo" as repo
    component "Service" as service
    component "ViewHolder" as viewholder
}

viewholder -(0- adapter
adapter -(0- service
models -(0- service
exceptions -(0- models
models -(0- api
api -(0- service
repo -(0- models
datamodels -(0- api
service -( android_ctc

@enduml