@startuml
'https://plantuml.com/component-diagram

left to right direction

hide circle
allowmixing
title Logical Architecture

package com.lvhm.covertocover as system_package {
    class "Main Activity" as main_activity
    package UI
    package Adapters
    package Service
    package Helper
    package Models
    package Listeners

    main_activity ..> UI
    UI ..> Service
    UI ..> Adapters
    UI ..> Listeners
    Service ..> Models
    Service ..> Helper
    Service ..> Listeners
    Listeners ..> Models
}
@enduml