@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as user
participant ":System" as sys

user -> sys: The user opens the app
user <-- sys: Display the app's main page view
user <-- sys: Show the user the three latest reviews
@enduml