@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as user
participant ":System" as sys

user <-- sys: Display the app's main page view

user -> sys: Click on the user icon
user <-- sys: Display the "Profile Page" view
@enduml