@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as user
participant ":System" as sys

user -> sys: The user opens the app
user <-- sys: Display the app's main page view

user -> sys: Click on the magnifier button
user <-- sys: Display an "Input ISBN" overlay

user -> sys: Input the book's ISBN
sys <-- sys: Search in the API for the inserted ISBN

alt API returns 200
user <-- sys: Display the "Book Information" view
else API returns 204
user <-- sys: Display an error message
'("Sorry, but the book was not found. Try to insert the ISBN manually")
end
@enduml