@startuml
'https://plantuml.com/use-case-diagram
left to right direction
title Use Case Diagram

actor "User" as usms
rectangle "Main Screen" {
    usecase "1. Search Book by Identifier" as UCMS1
    usecase "2. Click to go to Add Manual Book Screen" as UCMS2
    usecase "3. Click on any of the three latest reviews" as UCMS3
    usecase "4. See Your Yearly Statistics" as UCMS4
    usecase "5. Click on any of the four latest wishlisted books" as UCMS5
    usecase "6. Go through navbar buttons" as UCMS6
}
usms --> UCMS1
usms --> UCMS2
usms --> UCMS3
usms --> UCMS4
usms --> UCMS5
usms --> UCMS6

newpage
left to right direction
title Use Case Diagram

actor "User" as usps
rectangle "Profile Screen" {
    usecase "1. Click on the books on Your Bookshelf" as UCPS1
    usecase "2. Click on the reviews activity" as UCPS2
    usecase "3. Click on the wishlisted Books" as UCPS3
    usecase "4. See Your Review Plot" as UCPS4
    usecase "5. Go through navbar buttons" as UCPS5
}
usps --> UCPS1
usps --> UCPS2
usps --> UCPS3
usps --> UCPS4
usps --> UCPS5

newpage
left to right direction
title Use Case Diagram

actor "User" as uscs
rectangle "Camera Screen" {
    usecase "1. Scan barcode from the camera view" as UCCS1
    usecase "2. Go through navbar buttons" as UCCS2
}
uscs --> UCCS1
uscs --> UCCS2

newpage
left to right direction
title Use Case Diagram

actor "User" as usmap
rectangle "Map Screen" {
    usecase "1. See Libraries On The Map" as UCMAP1
    usecase "2. See list of the closest libraries" as UCMAP2
    usecase "3. Go through navbar buttons" as UCMAP3
}
usmap --> UCMAP1
usmap --> UCMAP2
usmap --> UCMAP3

newpage
left to right direction
title Use Case Diagram

actor "User" as usss
rectangle "Settings Screen" {
    usecase "1. Change profile picture" as UCSS1
    usecase "2. Change To Light/Dark Mode" as UCSS2
    usecase "3. Export app data" as UCSS3
    usecase "4. Force Saving Data" as UCSS4
    usecase "5. Go to Profile Settings" as UCSS5
    usecase "6. Go through navbar buttons" as UCSS6
}
usss --> UCSS1
usss --> UCSS2
usss --> UCSS3
usss --> UCSS4
usss --> UCSS5
usss --> UCSS6

newpage
left to right direction
title Use Case Diagram

actor "User" as uspss
rectangle "Profile Settings Screen" {
    usecase "1. Copy user token" as UCPSS1
    usecase "2. Change username" as UCPSS2
    usecase "3. Change your email" as UCPSS3
    usecase "4. Change phone number" as UCPSS4
    usecase "5. Change user address" as UCPSS5
    usecase "6. Change date format" as UCPSS6
}
uspss --> UCPSS1
uspss --> UCPSS2
uspss --> UCPSS3
uspss --> UCPSS4
uspss --> UCPSS5
uspss --> UCPSS6

newpage
left to right direction
title Use Case Diagram

actor "User" as usmbs
rectangle "Manual Book Screen" {
    usecase "1. Put an image to the book cover" as UCMBS1
    usecase "2. Change book status" as UCMBS2
    usecase "3. Fill Required Fields" as UCMBS3
    usecase "4. Fill Optional Fields" as UCMBS4
    usecase "5. Click save button" as UCMBS5
    usecase "6. Click cancel button" as UCMBS6
}
usmbs --> UCMBS1
usmbs --> UCMBS2
usmbs --> UCMBS3
usmbs --> UCMBS4
usmbs --> UCMBS5
usmbs --> UCMBS6

newpage
left to right direction
title Use Case Diagram

actor "User" as usbs
rectangle "Book Screen" {
    usecase "1. Click on book cover to zoom" as UCBS1
    usecase "2. Set book reading status" as UCBS2
    usecase "3. Add a review" as UCBS3
    usecase "4. See book metadata" as UCBS4
    usecase "5. Share book" as UCBS5
    usecase "6. See book's rating history" as UCBS6
}
usbs --> UCBS1
usbs --> UCBS2
usbs --> UCBS3
usbs --> UCBS4
usbs --> UCBS5
usbs --> UCBS6

@enduml