@startuml
'https://plantuml.com/use-case-diagram
left to right direction
title Use Case Diagram

actor "User" as usms
rectangle "Main Screen" {
    usecase "1. Click Scan Barcode Button" as UCMS1
    usecase "2. See Your Three Latest Reviews" as UCMS2
    usecase "3. See Your Yearly Statistics" as UCMS3
    usecase "4. See Your Five Latest Wishlisted Books" as UCMS4
    usecase "5. Search Book by Identifier" as UCMS5
    usecase "6. Go to Settings Page" as UCMS6
    usecase "7. Go to Profile Page" as UCMS7
    usecase "8. Go to Maps Page" as UCMS8
}
usms --> UCMS1
usms --> UCMS2
usms --> UCMS3
usms --> UCMS4
usms --> UCMS5
usms --> UCMS6
usms --> UCMS7
usms --> UCMS8

newpage
left to right direction
title Use Case Diagram

actor "User" as usps
rectangle "Profile Screen" {
    usecase "1. See Books on Your Bookshelf" as UCPS1
    usecase "2. See Reading Activity" as UCPS2
    usecase "3. See All Wishlisted Books" as UCPS3
    usecase "4. Create Your Own Booklist" as UCPS4
    usecase "5. See Your Review Plot" as UCPS5
}
usps --> UCPS1
usps --> UCPS2
usps --> UCPS3
usps --> UCPS4
usps --> UCPS5

newpage
left to right direction
title Use Case Diagram

actor "User" as usss
rectangle "Settings Screen" {
    usecase "1. Change To Light/Dark Mode" as UCSS1
    usecase "2. Change Data Format" as UCSS2
    usecase "3. Force Saving Data" as UCSS3
    usecase "4. Change Profile Settings" as UCSS4
}
usss --> UCSS1
usss --> UCSS2
usss --> UCSS3
usss --> UCSS4

newpage
left to right direction
title Use Case Diagram

actor "User" as usmap
rectangle "Map Screen" {
    usecase "1. See Libraries On The Map" as UCMAP1
}
usmap --> UCMAP1

@enduml