@startuml
'https://plantuml.com/sequence-diagram

autonumber

autonumber

actor "User" as user
participant ":System" as sys

user -> sys: Click on the add manual book icon
user <-- sys: Show add manual book scren

user -> sys: Click on the save button
user <-- sys : Saves the book into the container

@enduml