@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as user
participant ":Service" as sys

user -> sys: The user opens the app
user <-- sys: loadFragment(new MainScreen());
user -> sys: Click on the Add Manual Book Icon
user <-- sys: navigateToManualBookScreen(String isbn);
@enduml