@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as user
participant ":Service" as service

user -> service: Click on the profile page icon
user <-- service: loadFragment(new ProfileScreen());
service <-- service: reading_activity_section.setOnClickListener(View v);

user -> service: Click on the "Reviews Activity" button
user <-- service: new ReviewActivityScreen();

@enduml